import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import StarsCanvas from "@/components/StarBackground";
import Progressbar from "@/components/Progressbar";
import { Toaster } from "@/components/ui/sonner";
import ToastProvider from "@/components/toast";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transport App",
  description: "Generated by Jutech Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-black z-50 h-screen overflow-hidden")}>
        <Suspense>
          <Progressbar>
            <StarsCanvas />
            <Navbar />
            <Toaster />
            <ToastProvider />
            {children}
          </Progressbar>
        </Suspense>
      </body>
    </html>
  );
}
